-- Run this in MySQL Workbench to recreate all tables

CREATE TABLE IF NOT EXISTS Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(256) NOT NULL,
    FullName VARCHAR(100) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
    UpdatedAt DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Medications (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    OfficialName VARCHAR(150) NOT NULL,
    DisplayName VARCHAR(150) NULL,
    DosageValue DOUBLE NOT NULL DEFAULT 0,
    DosageUnit VARCHAR(20) NOT NULL DEFAULT '',
    IntakeInstructions VARCHAR(500) NOT NULL DEFAULT '',
    WeekdaySchedule JSON NULL,
    ScheduledTime TIME NULL,
    CreatedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
    UpdatedAt DATETIME NULL,
    IsActive TINYINT(1) NOT NULL DEFAULT 1,
    MedicineType VARCHAR(30) NOT NULL DEFAULT 'Tablet',
    Frequency VARCHAR(50) NOT NULL DEFAULT 'Once daily',
    ReminderTimes VARCHAR(200) NOT NULL DEFAULT '',
    MealTiming VARCHAR(30) NOT NULL DEFAULT 'Any Time',
    StartDate DATETIME NULL,
    EndDate DATETIME NULL,
    IsOngoing TINYINT(1) NOT NULL DEFAULT 1,
    IsArchived TINYINT(1) NOT NULL DEFAULT 0,
    RemainingPills INT NULL,
    LowStockAlertAt INT NULL,
    SnoozeMinutes INT NULL,
    CONSTRAINT FK_Medications_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS IntakeLogs (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    MedicationId INT NOT NULL,
    ScheduledDateTime DATETIME NOT NULL,
    ActionTimestamp DATETIME NULL,
    Status INT NOT NULL DEFAULT 1,
    LoggedAt DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
    CONSTRAINT FK_IntakeLogs_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    CONSTRAINT FK_IntakeLogs_Medications FOREIGN KEY (MedicationId) REFERENCES Medications(Id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
